name: poker_planning_client
description: PokerPlanning app frontend
dependencies:
  browser: any
  dart_config: any
  angular: "1.1.1"
  angular_node_bind: any
  http: any
  poker_planning_shared:
    path: ../shared
transformers:
- angular
dev_dependencies:
  test: 0.12.0-beta.5
dependency_overrides:
  route_hierarchical:
    version: any
    git: https://github.com/ArcBees/route.dart.git
