name: poker_planning_client
description: PokerPlanning app frontend
dependencies:
  browser: any
  dart_config: any
  angular: ">=1.1.0 <2.0.0"
  angular_node_bind: any
  poker_planning_shared:
    path: ../shared
dev_dependencies:
  unittest: any
transformers:
- angular
dependency_overrides:
  route_hierarchical:
    version: any
    git: https://github.com/ArcBees/route.dart.git
