name: poker_planning_server
version: 0.0.1
description: PokerPlanning app backend
dependencies:
  dart_config: any
  redstone: ">=0.5.21 <0.6.0"
  shelf: ">=0.5.7 <0.6.0"
  poker_planning_shared:
      path: ../shared
  logging_handlers: any
dev_dependencies:
  test: 0.12.0-beta.6
dependency_overrides:
  route_hierarchical:
    version: any
    git: https://github.com/ArcBees/route.dart.git
